### ISSUE TITLE
Unable to send funds to a coldstaking hot wallet address using segwit

### ISSUE THREAD

**Issue by thecrypt0hunter** [obsidianproject/Obsidian-StratisNode#13]
### Unable to send funds to a coldstaking hot wallet address using segwit UTXO

**Here's the error log:** 

```
fail: Stratis.Bitcoin.Features.ColdStaking.Controllers.ColdStakingController[0]
      Exception occurred: System.FormatException: Invalid base 58 string
         at NBitcoin.DataEncoders.Base58Encoder.DecodeData(String encoded) in /home/xxxxx/Obsidian-StratisNode/src/NBitcoin/DataEncoders/Base58Encoder.cs:line 121
         at NBitcoin.DataEncoders.Base58CheckEncoder.DecodeData(String encoded) in /home/xxxxx/Obsidian-StratisNode/src/NBitcoin/DataEncoders/Base58Encoder.cs:line 26
         at NBitcoin.BitcoinPubKeyAddress.IsValid(String base58, Network expectedNetwork) in /home/xxxxx/Obsidian-StratisNode/src/NBitcoin/BitcoinPubKeyAddress.cs:line 30
         at NBitcoin.BitcoinPubKeyAddress.Validate(String base58, Network expectedNetwork) in /home/xxxxx/Obsidian-StratisNode/src/NBitcoin/BitcoinPubKeyAddress.cs:line 21
         at NBitcoin.BitcoinPubKeyAddress..ctor(String base58, Network expectedNetwork) in /home/xxxxx/Obsidian-StratisNode/src/NBitcoin/BitcoinPubKeyAddress.cs:line 13
         at Stratis.Bitcoin.Features.ColdStaking.ColdStakingManager.GetColdStakingSetupTransaction(IWalletTransactionHandler walletTransactionHandler, String coldWalletAddress, String hotWalletAddress, String walletName, String walletAccount, String walletPassword, Money amount, Money feeAmount) in /home/xxxxxx/Obsidian-StratisNode/src/Stratis.Bitcoin.Features.ColdStaking/ColdStakingManager.cs:line 332
         at Stratis.Bitcoin.Features.ColdStaking.Controllers.ColdStakingController.SetupColdStaking(SetupColdStakingRequest request) in /home/xxxxx/Obsidian-StratisNode/src/Stratis.Bitcoin.Features.ColdStaking/Controllers/ColdStakingController.cs:line 186
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLQ1NVUO9OP8", Request id "0HLQ1NVUO9OP8:00000001": An unhandled exception was thrown by the application.
System.ArgumentNullException: Value cannot be null.
Parameter name: request
   at Stratis.Bitcoin.Utilities.Guard.NotNull[T](T value, String parameterName) in /home/xxxxx/Obsidian-StratisNode/src/Stratis.Bitcoin/Utilities/Guard.cs:line 49
   at Stratis.Bitcoin.Features.Wallet.Controllers.WalletController.SendTransaction(SendTransactionRequest request) in /home/xxxxx/Obsidian-StratisNode/src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs:line 939
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Stratis.Bitcoin.Features.Api.NoCacheMiddleware.InvokeAsync(HttpContext context) in /home/xxxxxx/Obsidian-StratisNode/src/Stratis.Bitcoin.Features.Api/NoCacheMiddleware.cs:line 22
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
**Steps to recreate:**

1. With the Full Node running, navigate to: https://obsidian.trustaking.com/activate.php
2. On Ubuntu, run the command $ `bash <( curl -s https://obsidian.trustaking.com/scripts/trustaking-cold-wallet-setup.sh )`
3. Follow the on screen instructions.

**Comment by thecrypt0hunter** [comment]
So the issue is that cold staking isn't setup to accept a segwit address.

**Comment by thecrypt0hunter** [comment]
I've reverted to a legacy address and now hitting the following error
```
fail: Stratis.Bitcoin.Features.Wallet.Controllers.WalletController[0]
      Exception occurred: System.IO.EndOfStreamException: No more byte to read
         at NBitcoin.BitcoinStream.ReadWriteBytes(Byte[]& data, Int32 offset, Int32 count) in /home/xxxxx/Obsidian-StratisNode/src/NBitcoin/BitcoinStream.cs:line 336
         at NBitcoin.BitcoinStream.ReadWriteNumber(UInt64& value, Int32 size) in /home/xxxxx/Obsidian-StratisNode/src/NBitcoin/BitcoinStream.cs:line 304
         at NBitcoin.BitcoinStream.ReadWrite(UInt32& data) in /home/xxxxx/Obsidian-StratisNode/src/NBitcoin/BitcoinStream.Partial.cs:line 303
         at NBitcoin.LockTime.ReadWrite(BitcoinStream stream) in /home/xxxxx/Obsidian-StratisNode/src/NBitcoin/LockTime.cs:line 83
         at NBitcoin.BitcoinStream.ReadWriteStruct[T](T& data) in /home/xxxxx/Obsidian-StratisNode/src/NBitcoin/BitcoinStream.cs:line 188
         at NBitcoin.Transaction.ReadWrite(BitcoinStream stream) in /home/xxxxx/Obsidian-StratisNode/src/NBitcoin/Transaction.cs:line 1326
         at NBitcoin.BitcoinSerializableExtensions.FromBytes(IBitcoinSerializable serializable, Byte[] bytes, ProtocolVersion version) in /home/xxxxx/Obsidian-StratisNode/src/NBitcoin/IBitcoinSerializable.cs:line 100
         at NBitcoin.PosTransaction..ctor(String hex, ProtocolVersion version) in /home/xxxxx/Obsidian-StratisNode/src/NBitcoin/BlockStake.cs:line 174
         at NBitcoin.PosConsensusFactory.CreateTransaction(String hex) in /home/xxxxx/Obsidian-StratisNode/src/NBitcoin/BlockStake.cs:line 263
         at NBitcoin.Network.CreateTransaction(String hex) in /home/xxxxx/Obsidian-StratisNode/src/NBitcoin/Network.cs:line 780
         at Stratis.Bitcoin.Features.Wallet.Controllers.WalletController.SendTransaction(SendTransactionRequest request) in /home/xxxxx/Obsidian-StratisNode/src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs:line 955
```

**Comment by dangershony** [comment]
Ok thanks this probably needs to ignore the segwit flag.

**Comment by dangershony** [comment]
This can be closed now right?
