### ISSUE TITLE
Create wallet failed with error

### ISSUE THREAD

**Issue by thecrypt0hunter** [obsidianproject/Obsidian-StratisNode#21]
Received with error when creating a wallet with the API:

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLQGU79MOO9S", Request id "0HLQGU79MOO9S:00000007": An unhandled exception was thrown by the application.
System.ArgumentNullException: Value cannot be null.
Parameter name: request
   at Stratis.Bitcoin.Utilities.Guard.NotNull[T](T value, String parameterName) in /home/xxxxx/projects/forks/Obsidian-StratisNode/src/Stratis.Bitcoin/Utilities/Guard.cs:line 49
   at Stratis.Bitcoin.Features.Wallet.Controllers.WalletController.Create(WalletCreationRequest request) in /home/xxxxx/projects/forks/Obsidian-StratisNode/src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs:line 142
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Stratis.Bitcoin.Features.Api.NoCacheMiddleware.InvokeAsync(HttpContext context) in /home/xxxx/projects/forks/Obsidian-StratisNode/src/Stratis.Bitcoin.Features.Api/NoCacheMiddleware.cs:line 22
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by dangershony** [comment]
@thecrypt0hunter odd I can not reproduce this error.
Is this still happening to you?

**Comment by thecrypt0hunter** [comment]
I re-tested this last night and its working fine - not sure if it was the latest update or just a glitch. I will close this now.
